[[sqlquerys]]
env = "demo"
address="10.5.100.1"
port= 9669
username = "root"
password = "nebula"
useHTTP2 = false
spacename = "bigmeta_release"
sql_script = "show hosts"
metrics_name="cluster_status"
labels_names= [ "Host","Status","Leader distribution","Partition distribution","Version"]
values_names=["Leader count"]


[[instances]]
env = "demo"
list = [ "10.5.100.1"]
metricsport=19559
urlsuffix = "/stats"
role="metad"

[[instances]]
env = "demo"
list =  [ "10.5.100.1","10.5.100.110","10.5.100.111"]
metricsport=19669
urlsuffix = "/stats"
role="graphd"

[[instances]]
env = "demo"
list = [ "10.5.100.1","10.5.100.110","10.5.100.111"]
metricsport=19779
urlsuffix = "/stats"
role="storaged"